"""simplify consent model add subject_email

Revision ID: 904a0ac923a9
Revises: 197d78911e78
Create Date: 2025-11-11 19:00:01.857576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904a0ac923a9'
down_revision: Union[str, Sequence[str], None] = '197d78911e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consents', sa.Column('subject_email', sa.String(length=255), nullable=True))
    op.alter_column('consents', 'subject_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('consents', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_consents_subject_email'), 'consents', ['subject_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consents_subject_email'), table_name='consents')
    op.alter_column('consents', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('consents', 'subject_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('consents', 'subject_email')
    # ### end Alembic commands ###
