"""add data right requests model

Revision ID: fe156d14f606
Revises: 7d9b463474c8
Create Date: 2025-11-11 19:10:16.743606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe156d14f606'
down_revision: Union[str, Sequence[str], None] = '7d9b463474c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_right_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('subject_email', sa.String(length=255), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('processed_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_right_requests_org_id'), 'data_right_requests', ['org_id'], unique=False)
    op.create_index(op.f('ix_data_right_requests_subject_email'), 'data_right_requests', ['subject_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_right_requests_subject_email'), table_name='data_right_requests')
    op.drop_index(op.f('ix_data_right_requests_org_id'), table_name='data_right_requests')
    op.drop_table('data_right_requests')
    # ### end Alembic commands ###
